bit_base_windows_minions:
  settings:
    dns_proto: static
    dns_servers:
      - 10.0.22.12
      - 10.0.22.1
    gateway: 10.0.22.1
    ntp_servers:
      - ptbtime1.ptb.de
      - ptbtime2.ptb.de
      - ptbtime3.ptb.de
    zabbix:
      active_host:
        host: argus.bienert.tech
        port: 10051
      passive_host:
        host: argus.bienert.tech
        port: 10050

  users: []

  minion_hosts: {}
