bit_base_windows_minions:
  settings:
    elasticsearch:
      - localhost:9200
    logstash: []
    kibana: 10.0.22.173:5601

    dns_proto: static
    dns_servers:
      - 10.0.22.12
      - 10.0.22.1

    gateway: 10.0.22.1

    ntp_servers:
      - ptbtime1.ptb.de
      - ptbtime2.ptb.de
      - ptbtime3.ptb.de

    apps:
      standard_apps: []
      chocolatey_apps: []
      # - name: zabbix-agent
      #   params: ""
      #   package_args: "-f -y"
      # - name: Firefox
      #   params: "/l:de-DE"
      #   package_args: "-f -y"

    zabbix:
      active_host:
        host: argus.bienert.tech
        port: 10051
      passive_host:
        host: argus.bienert.tech
        port: 10050

  users: []

  minion_hosts: {}
